theme: jekyll-theme-minimal
title: Ivan de Santiago
description: Computer Systems Engineer
logo: https://media-exp1.licdn.com/dms/image/C4E03AQF3-Dk5hNnPDQ/profile-displayphoto-shrink_800_800/0/1637187880955?e=1643241600&v=beta&t=sANHFAdqgzs2eyUogdvKEHbuHLCVeWawoEAYO6aThXE
show_downloads: false
