theme: jekyll-theme-minimal
title: Ivan de Santiago
description: Computer Systems Engineer
logo: https://media-exp1.licdn.com/dms/image/C4E03AQH0tP0XpBC5sA/profile-displayphoto-shrink_200_200/0/1637866378142?e=1643241600&v=beta&t=kK6WDAm9tkEPIDwyg8taqae5kOLsEJf6xdj54sIRUpQ
show_downloads: false
